### ISSUE TITLE
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0

### ISSUE THREAD

**Issue by nagolinc** [facebookresearch/chameleon#16]
when running 7b model on wsl2 (ubuntu)

root@loganrtx:~/chameleon# python -m chameleon.miniviewer

torch is using cuda 12.1

>>> import torch
>>> torch.cuda.is_available()
True
>>> print(torch.version.cuda)
12.1
>>>

I'm getting the following error:

...

Process SpawnProcess-2:
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/root/anaconda3/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/root/chameleon/chameleon/inference/chameleon.py", line 509, in _worker_impl
    for token in Generator(
  File "/root/chameleon/chameleon/inference/chameleon.py", line 403, in __next__
    piece = next(self.dyngen)
  File "/root/chameleon/chameleon/inference/utils.py", line 20, in __next__
    return next(self.gen)
  File "/root/chameleon/chameleon/inference/chameleon.py", line 279, in __next__
    tok = next(self.gen)
  File "/root/anaconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/chameleon/chameleon/inference/generation.py", line 91, in __next__
    next_tokens = self.token_selector(
  File "/root/chameleon/chameleon/inference/token_selector.py", line 31, in __call__
    return probs.multinomial(num_samples=1).squeeze(1)
  File "/root/anaconda3/lib/python3.10/site-packages/torch/utils/_device.py", line 77, in __torch_function__
    return func(*args, **kwargs)
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0
[W CudaIPCTypes.cpp:15] Producer process has been terminated before all shared CUDA tensors released. See Note [Sharing CUDA tensors]

```

**Comment by lshamis** [comment]
Can you share more information. Output of nvidia-smi. Generation inputs. ...

**Comment by nagolinc** [comment]
inputs
![image](https://github.com/facebookresearch/chameleon/assets/7775917/696f6c28-e3d7-4bb3-a6f7-1f8479b283b5)

![6303](https://github.com/facebookresearch/chameleon/assets/7775917/2e2380c4-429a-400b-a1cb-6298c71ea9e9)


nvidia-smi
```
^C(base) root@loganrtx:~/chameleon# nvidia-smi
Thu Jun 20 13:24:15 2024
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 560.00                 Driver Version: 560.38         CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3090        On  |   00000000:01:00.0  On |                  N/A |
|  0%   47C    P8             46W /  370W |    2106MiB /  24576MiB |      1%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A        39      G   /Xwayland                                   N/A      |
+-----------------------------------------------------------------------------------------+
```

**Comment by lshamis** [comment]
I'm not able to reproduce this. I'm assuming it's maybe running out of memory since the model without activation or cache is using 2.1GB out 2.45GB on the RTX 3090.
@jacobkahn Any ideas?

**Comment by nagolinc** [comment]
yeah, it looks like its OOM
