### ISSUE TITLE
The viewer does not work with the input image using the 7B model.

### ISSUE THREAD

**Issue by chiehpower** [facebookresearch/chameleon#17]
Hi all,

![screenshot-10-1-30-18-7654-1718855785550](https://github.com/facebookresearch/chameleon/assets/32332200/5dadda0a-680a-4be0-a177-469aade32b09)

I have tried using the 7B model, and it can be deployed successfully. However, when I tested it with several images, it seemed unable to handle image cases.

Is it a normal thing?

Thank you!

BR,
Chieh

**Comment by jacobkahn** [comment]
This is expected behavior. You can use less open-ended prompts which are more likely to trigger a safe response from the model.
