### ISSUE TITLE
Only support text, VQA  and Generate picture job are not working

### ISSUE THREAD

**Issue by hellangleZ** [facebookresearch/chameleon#23]
![image](https://github.com/facebookresearch/chameleon/assets/15274284/966a1ea4-8a9e-448c-a340-bc9bcf044801)
![image](https://github.com/facebookresearch/chameleon/assets/15274284/f47071ef-a2a0-4902-8e5c-8dd90b3933ed)

**Comment by hellangleZ** [comment]
> Image generation is not supported with the release checkpoint.
> 
> What's the type of the image you uploaded?

png, and jpg

**Comment by shllgtca** [comment]
@jacobkahn Does Meta plan to release the Chameleon image generation any time soon?

**Comment by lshamis** [comment]
Image ingestion in the miniviewer via drag & drop is hopefully fixed with https://github.com/facebookresearch/chameleon/pull/20
