### ISSUE TITLE
Hugging Face links in readme point to 404s

### ISSUE THREAD

**Issue by developersdigest** [facebookresearch/chameleon#3]
Congrats on the release! Just an FYI about the HF links in the readme.

<img width="852" alt="Screenshot 2024-06-18 at 3 06 14 PM" src="https://github.com/facebookresearch/chameleon/assets/124798203/4fe16344-db44-4a31-a16d-305456c68385">

**Comment by jacobkahn** [comment]
Thanks; work in progress. Should be active today.

**Comment by EwoutH** [comment]
Thanks for working on this! Any update to share?

**Comment by Divyanshsingh1910** [comment]
Hey, do we have any update on this?

**Comment by Iven2132** [comment]
@lshamis @jacobkahn Any update to share?

**Comment by jacobkahn** [comment]
This is taking longer than expected. I'll post an update here when things are live.

**Comment by Divyanshsingh1910** [comment]
Hey @jacobkahn, the Hugging Face link seems still inactive, do we have any updates on this?
Thanks

**Comment by Iven2132** [comment]
@jacobkahn The model is not good enough like other VLM, is there something I'm missing, or is it just the first version of this model?

**Comment by EwoutH** [comment]
@Iven2132 this is neither constructive or the right place for this. Open a [discussion](https://github.com/facebookresearch/chameleon/discussions) with a specific and constructive topic start if you want to discuss this further.
