### ISSUE TITLE
Download issue:[WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by pydemo** [facebookresearch/chameleon#34]
Running download:
 python -m chameleon.download_data "https:

Getting error:
```
this errors out: subprocess.check_call(["wget", "--continue", url, "-O", str(output_path)]) File "C:\Users\alex_\meta\chameleon\myenv\lib\site-packages\chameleon\download_data.py", line 12, in download_file subprocess.check_call(["wget", "--continue", url, "-O", str(output_path)]) File "C:\Program Files\Python310\lib\subprocess.py", line 364, in check_call retcode = call(*popenargs, **kwargs) File "C:\Program Files\Python310\lib\subprocess.py", line 345, in call with Popen(*popenargs, **kwargs) as p: File "C:\Program Files\Python310\lib\subprocess.py", line 971, in init self._execute_child(args, executable, preexec_fn, close_fds, File "C:\Program Files\Python310\lib\subprocess.py", line 1456, in _execute_child hp, ht, pid, tid = _winapi.CreateProcess(executable, args, FileNotFoundError: [WinError 2] The system cannot find the file specified
```
wget is there.
after adding shell=True to subprocess.check_call(["wget", "--continue", url, "-O", str(output_path)])
getting this:
```
&Download-Request-ID=2426055774252772', '-O', 'data\\tokenizer\\text_tokenizer.json']' returned non-zero exit status 1. 
``` 
when running actual command:
wget --continue https://*** Download-Request-ID=2426055774252772 -O data\tokenizer\text_tokenizer.json
```
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double
quotation marks ("&") to pass it as part of a string.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : AmpersandNotAllowed
```
After wrapping & in double quotes:
```
+ wget --continue https://dbj4kdlgwwbrp.cloudfront.net/tokenizer/text_t ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Invoke-WebRequest], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
```

**Comment by jsm69** [comment]
I'm facing the same issue @jacobkahn

**Comment by jacobkahn** [comment]
I assume this is on Windows? `wget` semantics may be different there, and inference also isn't supported officially on Windows at this time. cc @lshamis

**Comment by jsm69** [comment]
> I assume this is on Windows? `wget` semantics may be different there, and inference also isn't supported officially on Windows at this time. cc @lshamis

@jacobkahn No, It's happening in Linux Debian GCP VM

**Comment by lshamis** [comment]
The error shared by @pydemo is an issue with wget on Windows, which is not supported.
Adding shell=True runs the wget in PowerShell, and the url is specified for Linux shells.

@jsm69 If you have an issue specific to Linux, please open another issue.

**Comment by nonameforpirate2** [comment]
The problem comes because the chameleon.download_data.sh file has a unix format and you are trying to perform an installation on windows. It basically has a difference it terms of spacing which is 'CRLF' and 'LF'. Thus you get the error chameleon was built on unix and its programmers are expecting you to install it on unix. Thus, it does not work. Run everything on unix and it works and yes, use python 3.11. (Now, that I have my Penny moment to shine. I am expecting a star in my forehead :))
