### ISSUE TITLE
Questions about image decoder.

### ISSUE THREAD

**Issue by zzzqzhou** [facebookresearch/chameleon#37]
Hi authors,

Thanks for your amazing jobs. I have tried your models and have some question about image decoder.

I read the document and you said that these released models are not able to generate images. But I notice that you provide the "ImageDecoder" class and "decode_image" function in chameleon/inference/chamleon.py. I was wondering whether the provided models can generated image tokens.

I tried two things:

1. I used the vqgan ckpt to tokenize an image and get the image tokens, then I use "decode_image" to reconstruct the image from image tokens and it worked. It seems that the image detokenizer can work. I don't know if it is correct.
2. I tried to prompt the model to generate image tokens and then use "decode_image" to generate images from these tokens. What I did was changing "txt" argument to False and "img" argument to True in Options class. (I think this will force the model to generate the image tokens. Is it correct?) I got output tokens of length 1024 (same as number of tokens of a single image). But the decoded image from these tokens is strange. 
![example](https://github.com/facebookresearch/chameleon/assets/36720780/a979451d-8c60-4fee-91d6-6b7b0b65e93f)
 It seems the model can not generate image tokens and if forced to do so, it will just generate random tokens.

What I want to know is that whether you trained the model not to generate image tokens? Is this why released models cannot generate images?

Thank you

**Comment by zzzqzhou** [comment]
Does it mean you trained the models not to generate image tokens?

**Comment by AbrahamSanders** [comment]
My guess: they masked out the loss over the image token positions. This way the model would learn to condition text on the image tokens but not actually generate them.

I hope the full models are released soon!
