### ISSUE TITLE
Multimodal results for assessing architectural plans

### ISSUE THREAD

**Issue by steveterry66** [facebookresearch/chameleon#45]
Hi, this is a use case that I'm looking for. I have attached the screenshot results with an erroneous interpretation (The dimensions of the yard are 10x25.). Please advise on how I could improve the results. Also, I have attached the original input jpeg, and a prompt of what I really want.
[Manshed chameloen prompt.txt](https://github.com/user-attachments/files/16093556/Manshed.chameloen.prompt.txt)
![manshed](https://github.com/facebookresearch/chameleon/assets/169585440/91c277bf-1b38-44d9-aec3-87fe0e8dd333)
![chameleonResults](https://github.com/facebookresearch/chameleon/assets/169585440/bec09233-b673-49b5-911c-dee884ac22a1)

BTW, it runs okay on my laptop with a Nvidia 4070

**Comment by lshamis** [comment]
We're not able to help with very specific use cases. Maybe try a chain of thought asking for explicit ocr and asking it to enumerate the calculation. Not sure. Good luck. Closing the issue.
