### ISSUE TITLE
Why Answers are different for repeating the same text question + same input image

### ISSUE THREAD

**Issue by usajid14** [facebookresearch/chameleon#47]
Hi,

I have noticed that model answers vary wildly if we repeat the same question + input image. Can you give any insights on the reason behind it? Thank you!

**Comment by jacobkahn** [comment]
Setting the temperature to 1 should give you repeatable outputs for generation (the default is not 1).

**Comment by EntilZha** [comment]
To add a bit more, double check that you're setting the seed to the same value each time.
