### ISSUE TITLE
Accessing VQGAN Checkpoint

### ISSUE THREAD

**Issue by KL-VC** [facebookresearch/chameleon#51]
Hi, great work here. I am granted access to hugging face checkpoints but on hugging face there is no VQGAN part. According to your downloading code, there should be a email with a certain link. And through that link, users are supposed to download VQGAN.ckpt. How can I apply for that link?

**Comment by neoyxm** [comment]
May I know if you found the solution to download these check points?

**Comment by lshamis** [comment]
The VQGAN checkpoint is in the tokenizer directory

**Comment by david-jx-second** [comment]
> The VQGAN checkpoint is in the tokenizer directory

Could you please share the link? I did not find it. 
Thanks in advance!

**Comment by zyandtom** [comment]
anybody find it? I fount it missed in chameleon huggingface https://huggingface.co/facebook/chameleon-7b, even worse, my request have been rejected...
