### ISSUE TITLE
The generated image does not make any sense.

### ISSUE THREAD

**Issue by MaureenZOU** [facebookresearch/chameleon#60]
I have tried the model with miniviewer, under the default setting, the generated image looks very strange, the text generation part seems reasonable. It would be really appreciated if anyone could help.
<img width="651" alt="Screenshot 2024-07-21 at 9 29 03 PM" src="https://github.com/user-attachments/assets/2211cdc6-3789-4264-b26a-6754e1f7e991">

**Comment by thaoshibe** [comment]
@MaureenZOU, they didn't release the image generation ability.
For image generation, you might refer to this: https://github.com/GAIR-NLP/anole?tab=readme-ov-file

**Comment by MaureenZOU** [comment]
Thanks Thao! Then this makes sense to me.
