### ISSUE TITLE
Training code for VQ-GAN

### ISSUE THREAD

**Issue by karrykkk** [facebookresearch/chameleon#65]
Thank you for your excellent work!

Do you have any plans to release the training code for VQ-GAN? Alternatively, could you share the checkpoint for the VQ-GAN discriminator & optimizer that corresponds to your model weights for further fine-tuning? I would be very grateful if you could give me some help！

Thanks in advance!

**Comment by lshamis** [comment]
The VQ-GAN checkpoint is in the tokenizer directory. We have no plans to release any more code at this time.
