### ISSUE TITLE
The images generated by Chameleon are completely meaningless

### ISSUE THREAD

**Issue by zsj555** [facebookresearch/chameleon#67]
Why are the images generated by Chameleon completely meaningless? If it doesn't even have the ability to generate images, why dare you call it a unified multimodal model? Your research department will probably be cut off.

**Comment by w-shin-int** [comment]
#37

**Comment by Yaohui-Zhang** [comment]
Hi, I encountered the same issue. I ran the viewer successfully but couldn't see the image being displayed (only text). Is this what you experienced as well?

**Comment by EntilZha** [comment]
The model described in the paper is a unified multimodal model, but the released weights do not include that capability. If you are interested in multimodal generation, you might check this repository out which begins with the released Chameleon weights and finetunes a subset of weights that seems to make it able to generate images https://github.com/GAIR-NLP/anole.
